#!/usr/bin/env python
# -*- coding:utf-8 -*-

import RPi.GPIO as GPIO
import sys

if len(sys.argv) == 2:
    pin = int(sys.argv[1])
    GPIO.setwarnings(False)
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(pin, GPIO.IN)
    print 'The value of ' + str(pin) + ' is: ' + str(GPIO.input(pin))
elif len(sys.argv) == 3:
    pin = int(sys.argv[1])
    v = int(sys.argv[2])
    GPIO.setwarnings(False)
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(pin, GPIO.OUT)
    GPIO.output(pin, v)
    print 'Set ' + str(pin) + ' to ' + str(v)
else:
	print "try gpio 24 or gpio 24 1"