#!/bin/sh
#
# Homie service
#

set -e
PACKAGE_NAME=Homie
PACKAGE_DESC="Homie Service"
LOG_FILE="/var/log/homie.log"
DIR="/home/pi/mine/project/IHS/pi/"
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:${PATH}
start() {
     echo "Starting Lights service"
     nohup python $DIR/jobLights.py >${LOG_FILE} 2>&1 &
     echo "Starting Temperature&Humidity Service"
     nohup python $DIR/jobTempHum.py >${LOG_FILE} 2>&1 &
     echo "Starting Infrared Service"
     nohup python $DIR/jobInfrared.py >${LOG_FILE} 2>&1 &
     echo "Starting Monitor Service"
     nohup motion -n >${LOG_FILE} 2>&1 &
}
stop() {
     kill -9 `ps aux | grep 'jobLights.py' | grep -v grep | awk '{print $2}'` >/dev/null 2>&1 || true
     echo "Lights Service Stopped"
     kill -9 `ps aux | grep 'jobTempHum.py' | grep -v grep | awk '{print $2}'` >/dev/null 2>&1 || true
     echo "Temperature&Humidity Service Stopped"
     kill -9 `ps aux | grep 'jobInfrared.py' | grep -v grep | awk '{print $2}'` >/dev/null 2>&1 || true
     echo "Infrared Stopped"
     kill -9 `ps aux | grep 'motion' | grep -v grep | awk '{print $2}'` >/dev/null 2>&1 || true
     echo "Monitor Stopped"
}
restart() {
     stop || true
     sleep 1
     start
}
usage() {
     N=$(basename "$0")
          echo "Usage: [sudo] $N {start|stop|restart}" >&2
          exit 1
}

if [ "$(id -u)" != "0" ]; then
     echo "please use sudo to run ${PACKAGE_NAME}"
     exit 0
fi
# `readlink -f` won't work on Mac, this hack should work on all systems.
cd $(python -c "import os; print os.path.dirname(os.path.realpath('$0'))")
case "$1" in
     start)
     start
     ;;
     stop)
     stop
     ;;
     #reload)
     restart | force-reload)
     restart
     ;;
     *)
     start
     ;;
     esac
exit 0


